#!/usr/bin/env bash
# This script displays information about subdomains

domain=$1
subdomain=$2

display_info() {
    local subdomain=$1
    local record_info=$(dig +short -t A ${subdomain}.${domain})
    
    if [[ -n "$record_info" ]]; then
        echo "The subdomain ${subdomain} is an A record and points to ${record_info}"
    else
        echo "The subdomain ${subdomain} does not have an A record"
    fi
}

if [[ -n "$subdomain" ]]; then
    display_info $subdomain
else
    for subdomain in www lb-01 web-01 web-02; do
        display_info $subdomain
    done
fi
