#!/usr/bin/env bash
# shell commands steps for the installation of nginx
sudo apt-get update
sudo apt-get install nginx
sudo ufw "Nginx HTTP"
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx reload
