#!/usr/bin/env bash

# Update your local node's package lists
sudo apt-get update -y

# Install nginx
sudo apt-get install -y nginx

# Start nginx
sudo service nginx start

# Create a new default site configuration with "Hello World!"
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        return 200 'Hello World!';
        add_header Content-Type text/plain;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Restart nginx to apply the changes
sudo service nginx restart
