#!/usr/bin/env bash
# Installing nginx on th web server

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/html/index.html

# configuration testing
sudo nginx -t

sudo service nginx reload
