#!/usr/bin/env bash
# Script that installs Nginx server and redirects.
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.github.com/MosesOdinaka permanent;\n\t}\n"

sudo sed -i "53s|.*|$redirect|" /etc/nginx/sites-enabled/default

sudo /etc/init.d/nginx restart
