#!/usr/bin/env bash
# Define the Nginx configuration with the custom header

sudo apt-get update -y

sudo apt-get install nginx -y

echo "Hello World!" | sudo dd status=none of=/var/www/html/index.html

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

NEW_RULE="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.github.com/MosesOdinaka;\n\t}\n"

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default

NEW_RULE="\\\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\tinternal;\n\t}\n"

sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default

# Define the Nginx configuration with the custom header
config='server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location / {
        add_header X-Served-By $hostname;
        try_files $uri $uri/ =404;
    }
}'

# Write the configuration to the default file
echo "$config" | sudo tee /etc/nginx/sites-available/default

# Test the configuration
sudo nginx -t

# If the test is successful, reload Nginx
if [ $? -eq 0 ]
then
    sudo systemctl reload nginx
else
    echo "Nginx configuration test failed"
fi
