#!/usr/bin/env bash
# Displays a list of all running processes, for all users,
# including those which might not have a TTY,
# in a user-oriented format, showing process hierarchy.

output_pid=$(ps axo user,pid,args --sort=-%cpu)

echo "USER       PID COMMAND"
echo "$output_pid" | while read -r line
do
    if [[ $line != *"PID COMMAND"* && $line != *"ps axo"* ]]; then
        tabs=$(echo -e "$line" | awk '{ print gsub(/\t/, "") }')
        prefix=""
        for ((i=0; i<tabs; i++)); do
            prefix=$prefix"  |"
        done
        echo "$prefix-- $line"
    fi
done
